apiVersion: v1
kind: Service
metadata:
   name: nginx
   labels: service-demo
spec:
  selectors:
    purpose: service-demo
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80 #service port
      target port: 80 #container port




---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    purpose: service-demo
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx    